[package]
name = "aoc"
version = "0.1.0"
authors = ["Prefectly Cromulent <prefectly.cromulent@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
regex = "1"